### ISSUE TITLE
Generate doesn't work on Koha 23.11

### ISSUE THREAD

**Issue by rafko** [inLibro/koha-plugin-carrousel#16]
It seems in new Koha at least in version 23.11, this plugin can't generate carrousel. 
Getting error:
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::mysql::st execute failed: Unknown column 'title' in 'where clause' at /usr/share/koha/lib/Koha/Objects.pm line 185
Probably it's caused by: "Bug 31383: Create a parent-child DB relation for additional content", it introducing separate tables additional_contents and additional_contents_localizations. Plugin still uses old schema with one table.

**Comment by fridobox** [comment]
Indeed I confirm

**Comment by ericbegin** [comment]
@rafko,

Thanks for reporting this issue.  We just fixed it.

Let us know if you still have any issue.

Thanks !
